### ISSUE TITLE
error compiling example

### ISSUE THREAD

**Issue by nanu-c** [frauzufall/ofx2DMapping#13]
I've just copied pasted the example in a new project, included the addons and got lot of errors:
[gist](https://gist.github.com/nanu-c/048d8d6244b20c585d858e7025a063e9)
- `/home/nanu/Projekte/openFrameworks/addons/ofxTriangle/libs/Triangle/include/dpoint.hpp:541:8: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘std::istream {aka std::basic_istream<char>}’)
      << is << std::endl;` -> solution commenting the line
- ofxSortableList needs `/home/nanu/Projekte/openFrameworks/addons/ofxSortableList/src/ofxSortableList.h:3:28: fatal error: ofxGuiExtended.h: Datei oder Verzeichnis nicht gefunden`
- when I add that and ofxGui and ofxGuiExtended is defined I get: `/addons/ofxGuiExtended/src/containers/ofxGuiGroup.h:52:7: error: redefinition of ‘class ofxGuiGroup’` So I replaced ofxGui.h with ofxGuiExtended.h
- then the error is `openFrameworks/addons/ofx2DMapping/src/ofx2DFormMapping.h:4:22: fatal error: ofxPanel.h: Datei oder Verzeichnis nicht gefunden` -> hat to replace that and some others with ofxGuiPanel etc.

**Comment by frauzufall** [comment]
Jepp as it says [here](https://github.com/frauzufall/ofxGuiExtended) the version of this addon compatible to the new ofxGuiExtended version is not online yet. This master branch here is only working with the old ofxSortableList and ofxGui. 
I updated the code already, but I still have to fix the example and I did not find the time yet.

**Comment by frauzufall** [comment]
Sorry for being confusing! Give me a bit more time and I will get this done.

**Comment by nanu-c** [comment]
okey I will look in that :)
and thank you for your great work!

**Comment by nanu-c** [comment]
And i didn't saw the little notice

**Comment by frauzufall** [comment]
Yeah sorry. It's just a bit much that has to be changed at once right now.

**Comment by nanu-c** [comment]
I was working a lot with the "old" ofxGuiExtended and I understand why the changes are really useful, but I need to get used to it to change things.
For short, i think  I am going to use an old ofxGuiExtended and sortedList version :)

**Comment by frauzufall** [comment]
Take your time ;)
